### PR TITLE
Update internals

### PR DESCRIPTION
**Pull request by dlongley**

### CODE REVIEW

**Review by mattcollier — COMMENTED** [review]
I'm not sure if this PR is still a WIP, but there are several TODO's about switching to named parameters.

**Comment by dlongley** [comment]
@mattcollier,

Those TODOs won't be addressed in this PR. This PR is not intended to change the public API in any significant -- so a patch or minor update only.

I don't think I'm going to get to the API updates in those TODOs for a while -- and it would involve changing a number of other modules that may be too much work in the immediate term. So the goal here is to just make a step towards it. This also means I won't be changing "PermissionDenied" here yet. That will happen when the API changes and we do a major release.

**Comment by dlongley** [comment]
So this PR is not a WIP, please review.

**Review by mattcollier — APPROVED** [review]
LGTM.

**Pull request merged**
